name: pretendo
recipe: lamp
config:
  php: '8.3'
  via: apache:2.4
  webroot: .
  database: mongo:8.0
  xdebug: false
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - mongo8
  mongodb:
    type: mongo:8.0
  redis:
    type: redis
    portforward: true
  node:
    type: node
    build:
      - yarn install
tooling:
  yarn:
    service: node
